package com.example.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.services.TableService;

/**
 * Created by shailendra.singh on 4/20/17.
 */
@DynamoDBTable(tableName = TableService.TABLE_NAME)
public class Person {

    private String uuid;
    private String firstName;
    private String lastName;
    private int age ;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @DynamoDBAttribute(attributeName = "firstname")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastname")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "age")
    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
